M48
; DRILL file {KiCad 6.0.7-f9a2dced07~116~ubuntu20.04.1} date Thu 13 Oct 2022 01:02:21 BST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-13T01:02:21+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-f9a2dced07~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X114.0Y-79.95
X115.0Y-162.95
X150.0Y-92.95
X150.0Y-162.95
T0
M30
